#ifndef _HOOSHO_CGI_UE_COMMON_H_
#define _HOOSHO_CGI_UE_COMMON_H_
	

#define REQ_ACTION_CONFIG  "config"

#define REPLY_STATE_SUCC "SUCCESS"
#define REPLY_STATE_SIZE_EXCEED "文件大小超出 upload_max_filesize 限制"
#define REPLY_STATE_UPLOAD_EMPTY "上传文件为空"
#define REPLY_STATE_CONFIG_PARSE_FAILED "解析UE配置失败"
#define REPLY_STATE_CONFIG_PARAM_ABSENT "UE配置参数缺失"
#define REPLY_STATE_IVALID_PARAM "无效的请求参数"
#define REPLY_STATE_SERVER_BUSY "服务器繁忙"


#define UE_RESOURCE_TYPE_IMAGE 1
#define UE_RESOURCE_TYPE_VIDEO 2
#define UE_RESOURCE_TYPE_FILE 99

enum CGI_RET_CODE
{
	CGI_RET_CODE_SUCC = 0,
	CGI_RET_CODE_CONTENT_EMPTY = 10001,
	CGI_RET_CODE_SERVER_BUSY = 10002,
	CGI_RET_CODE_CONTENT_OVERFLOW = 10003,
	CGI_RET_CODE_CONTENT_NOTFOUND = 10004,
};


#endif

