# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_noticenotify.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import comm_struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_noticenotify.proto',
  package='hoosho.noticenotify',
  serialized_pb='\n\x16msg_noticenotify.proto\x12\x13hoosho.noticenotify\x1a\x11\x63omm_struct.proto\"*\n\nTypeStatus\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\r\"@\n\x14QueryNoticeNotifyReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x12\n\nopenid_md5\x18\x02 \x01(\x04\"&\n\x14QueryNoticeNotifyRes\x12\x0e\n\x06status\x18\x01 \x01(\r\"V\n\x1cQueryNoticeNotifyTypeListReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x12\n\nopenid_md5\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\r\"Y\n\x1cQueryNoticeNotifyTypeListRes\x12\x39\n\x10type_status_list\x18\x01 \x03(\x0b\x32\x1f.hoosho.noticenotify.TypeStatus\"r\n\x14QueryNoticeRecordReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x12\n\nopenid_md5\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\x10\n\x08limit_ts\x18\x04 \x01(\x04\x12\x10\n\x08pagesize\x18\x05 \x01(\r\"S\n\x14QueryNoticeRecordRes\x12;\n\x12notice_record_list\x18\x01 \x03(\x0b\x32\x1f.hoosho.commstruct.NoticeRecord\"O\n\x15UpdateNoticeRecordReq\x12\x36\n\rnotice_record\x18\x01 \x01(\x0b\x32\x1f.hoosho.commstruct.NoticeRecord\"\x17\n\x15UpdateNoticeRecordRes\"L\n\x12\x41\x64\x64NoticeRecordReq\x12\x36\n\rnotice_record\x18\x01 \x01(\x0b\x32\x1f.hoosho.commstruct.NoticeRecord\"\x14\n\x12\x41\x64\x64NoticeRecordRes\"M\n\x13ReadNoticeRecordReq\x12\x36\n\rnotice_record\x18\x01 \x01(\x0b\x32\x1f.hoosho.commstruct.NoticeRecord\"\x15\n\x13ReadNoticeRecordRes\"b\n\x15\x44\x65leteNoticeRecordReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x12\n\nopenid_md5\x18\x02 \x01(\x04\x12\x11\n\tcreate_ts\x18\x03 \x01(\x04\x12\x0c\n\x04type\x18\x04 \x01(\r\"\x17\n\x15\x44\x65leteNoticeRecordRes')




_TYPESTATUS = _descriptor.Descriptor(
  name='TypeStatus',
  full_name='hoosho.noticenotify.TypeStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='hoosho.noticenotify.TypeStatus.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='hoosho.noticenotify.TypeStatus.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=108,
)


_QUERYNOTICENOTIFYREQ = _descriptor.Descriptor(
  name='QueryNoticeNotifyReq',
  full_name='hoosho.noticenotify.QueryNoticeNotifyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.noticenotify.QueryNoticeNotifyReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.noticenotify.QueryNoticeNotifyReq.openid_md5', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=110,
  serialized_end=174,
)


_QUERYNOTICENOTIFYRES = _descriptor.Descriptor(
  name='QueryNoticeNotifyRes',
  full_name='hoosho.noticenotify.QueryNoticeNotifyRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='hoosho.noticenotify.QueryNoticeNotifyRes.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=176,
  serialized_end=214,
)


_QUERYNOTICENOTIFYTYPELISTREQ = _descriptor.Descriptor(
  name='QueryNoticeNotifyTypeListReq',
  full_name='hoosho.noticenotify.QueryNoticeNotifyTypeListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.noticenotify.QueryNoticeNotifyTypeListReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.noticenotify.QueryNoticeNotifyTypeListReq.openid_md5', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='hoosho.noticenotify.QueryNoticeNotifyTypeListReq.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=302,
)


_QUERYNOTICENOTIFYTYPELISTRES = _descriptor.Descriptor(
  name='QueryNoticeNotifyTypeListRes',
  full_name='hoosho.noticenotify.QueryNoticeNotifyTypeListRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_status_list', full_name='hoosho.noticenotify.QueryNoticeNotifyTypeListRes.type_status_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=393,
)


_QUERYNOTICERECORDREQ = _descriptor.Descriptor(
  name='QueryNoticeRecordReq',
  full_name='hoosho.noticenotify.QueryNoticeRecordReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.noticenotify.QueryNoticeRecordReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.noticenotify.QueryNoticeRecordReq.openid_md5', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='hoosho.noticenotify.QueryNoticeRecordReq.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_ts', full_name='hoosho.noticenotify.QueryNoticeRecordReq.limit_ts', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='hoosho.noticenotify.QueryNoticeRecordReq.pagesize', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=395,
  serialized_end=509,
)


_QUERYNOTICERECORDRES = _descriptor.Descriptor(
  name='QueryNoticeRecordRes',
  full_name='hoosho.noticenotify.QueryNoticeRecordRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notice_record_list', full_name='hoosho.noticenotify.QueryNoticeRecordRes.notice_record_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=511,
  serialized_end=594,
)


_UPDATENOTICERECORDREQ = _descriptor.Descriptor(
  name='UpdateNoticeRecordReq',
  full_name='hoosho.noticenotify.UpdateNoticeRecordReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notice_record', full_name='hoosho.noticenotify.UpdateNoticeRecordReq.notice_record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=596,
  serialized_end=675,
)


_UPDATENOTICERECORDRES = _descriptor.Descriptor(
  name='UpdateNoticeRecordRes',
  full_name='hoosho.noticenotify.UpdateNoticeRecordRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=677,
  serialized_end=700,
)


_ADDNOTICERECORDREQ = _descriptor.Descriptor(
  name='AddNoticeRecordReq',
  full_name='hoosho.noticenotify.AddNoticeRecordReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notice_record', full_name='hoosho.noticenotify.AddNoticeRecordReq.notice_record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=702,
  serialized_end=778,
)


_ADDNOTICERECORDRES = _descriptor.Descriptor(
  name='AddNoticeRecordRes',
  full_name='hoosho.noticenotify.AddNoticeRecordRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=780,
  serialized_end=800,
)


_READNOTICERECORDREQ = _descriptor.Descriptor(
  name='ReadNoticeRecordReq',
  full_name='hoosho.noticenotify.ReadNoticeRecordReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notice_record', full_name='hoosho.noticenotify.ReadNoticeRecordReq.notice_record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=802,
  serialized_end=879,
)


_READNOTICERECORDRES = _descriptor.Descriptor(
  name='ReadNoticeRecordRes',
  full_name='hoosho.noticenotify.ReadNoticeRecordRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=881,
  serialized_end=902,
)


_DELETENOTICERECORDREQ = _descriptor.Descriptor(
  name='DeleteNoticeRecordReq',
  full_name='hoosho.noticenotify.DeleteNoticeRecordReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.noticenotify.DeleteNoticeRecordReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.noticenotify.DeleteNoticeRecordReq.openid_md5', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_ts', full_name='hoosho.noticenotify.DeleteNoticeRecordReq.create_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='hoosho.noticenotify.DeleteNoticeRecordReq.type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=904,
  serialized_end=1002,
)


_DELETENOTICERECORDRES = _descriptor.Descriptor(
  name='DeleteNoticeRecordRes',
  full_name='hoosho.noticenotify.DeleteNoticeRecordRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1004,
  serialized_end=1027,
)

_QUERYNOTICENOTIFYTYPELISTRES.fields_by_name['type_status_list'].message_type = _TYPESTATUS
_QUERYNOTICERECORDRES.fields_by_name['notice_record_list'].message_type = comm_struct_pb2._NOTICERECORD
_UPDATENOTICERECORDREQ.fields_by_name['notice_record'].message_type = comm_struct_pb2._NOTICERECORD
_ADDNOTICERECORDREQ.fields_by_name['notice_record'].message_type = comm_struct_pb2._NOTICERECORD
_READNOTICERECORDREQ.fields_by_name['notice_record'].message_type = comm_struct_pb2._NOTICERECORD
DESCRIPTOR.message_types_by_name['TypeStatus'] = _TYPESTATUS
DESCRIPTOR.message_types_by_name['QueryNoticeNotifyReq'] = _QUERYNOTICENOTIFYREQ
DESCRIPTOR.message_types_by_name['QueryNoticeNotifyRes'] = _QUERYNOTICENOTIFYRES
DESCRIPTOR.message_types_by_name['QueryNoticeNotifyTypeListReq'] = _QUERYNOTICENOTIFYTYPELISTREQ
DESCRIPTOR.message_types_by_name['QueryNoticeNotifyTypeListRes'] = _QUERYNOTICENOTIFYTYPELISTRES
DESCRIPTOR.message_types_by_name['QueryNoticeRecordReq'] = _QUERYNOTICERECORDREQ
DESCRIPTOR.message_types_by_name['QueryNoticeRecordRes'] = _QUERYNOTICERECORDRES
DESCRIPTOR.message_types_by_name['UpdateNoticeRecordReq'] = _UPDATENOTICERECORDREQ
DESCRIPTOR.message_types_by_name['UpdateNoticeRecordRes'] = _UPDATENOTICERECORDRES
DESCRIPTOR.message_types_by_name['AddNoticeRecordReq'] = _ADDNOTICERECORDREQ
DESCRIPTOR.message_types_by_name['AddNoticeRecordRes'] = _ADDNOTICERECORDRES
DESCRIPTOR.message_types_by_name['ReadNoticeRecordReq'] = _READNOTICERECORDREQ
DESCRIPTOR.message_types_by_name['ReadNoticeRecordRes'] = _READNOTICERECORDRES
DESCRIPTOR.message_types_by_name['DeleteNoticeRecordReq'] = _DELETENOTICERECORDREQ
DESCRIPTOR.message_types_by_name['DeleteNoticeRecordRes'] = _DELETENOTICERECORDRES

class TypeStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TYPESTATUS

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.TypeStatus)

class QueryNoticeNotifyReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICENOTIFYREQ

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.QueryNoticeNotifyReq)

class QueryNoticeNotifyRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICENOTIFYRES

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.QueryNoticeNotifyRes)

class QueryNoticeNotifyTypeListReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICENOTIFYTYPELISTREQ

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.QueryNoticeNotifyTypeListReq)

class QueryNoticeNotifyTypeListRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICENOTIFYTYPELISTRES

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.QueryNoticeNotifyTypeListRes)

class QueryNoticeRecordReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICERECORDREQ

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.QueryNoticeRecordReq)

class QueryNoticeRecordRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICERECORDRES

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.QueryNoticeRecordRes)

class UpdateNoticeRecordReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATENOTICERECORDREQ

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.UpdateNoticeRecordReq)

class UpdateNoticeRecordRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATENOTICERECORDRES

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.UpdateNoticeRecordRes)

class AddNoticeRecordReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDNOTICERECORDREQ

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.AddNoticeRecordReq)

class AddNoticeRecordRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDNOTICERECORDRES

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.AddNoticeRecordRes)

class ReadNoticeRecordReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _READNOTICERECORDREQ

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.ReadNoticeRecordReq)

class ReadNoticeRecordRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _READNOTICERECORDRES

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.ReadNoticeRecordRes)

class DeleteNoticeRecordReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETENOTICERECORDREQ

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.DeleteNoticeRecordReq)

class DeleteNoticeRecordRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETENOTICERECORDRES

  # @@protoc_insertion_point(class_scope:hoosho.noticenotify.DeleteNoticeRecordRes)


# @@protoc_insertion_point(module_scope)
