# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_pa.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import comm_struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_pa.proto',
  package='hoosho.pa',
  serialized_pb='\n\x0cmsg_pa.proto\x12\thoosho.pa\x1a\x11\x63omm_struct.proto\"6\n\x08PAAddReq\x12*\n\x07pa_info\x18\x01 \x01(\x0b\x32\x19.hoosho.commstruct.PAInfo\"\n\n\x08PAAddRes\"9\n\x0bPAUpdateReq\x12*\n\x07pa_info\x18\x01 \x01(\x0b\x32\x19.hoosho.commstruct.PAInfo\"\r\n\x0bPAUpdateRes\" \n\x0bPADeleteReq\x12\x11\n\tappid_md5\x18\x01 \x01(\x04\"\r\n\x0bPADeleteRes\"\x1d\n\x08PAGetReq\x12\x11\n\tappid_md5\x18\x01 \x01(\x04\"6\n\x08PAGetRes\x12*\n\x07pa_info\x18\x01 \x01(\x0b\x32\x19.hoosho.commstruct.PAInfo\",\n\x13ParsePreAuthCodeReq\x12\x15\n\rpre_auth_code\x18\x01 \x01(\t\"R\n\x13ParsePreAuthCodeRes\x12;\n\x10user_detail_info\x18\x01 \x01(\x0b\x32!.hoosho.commstruct.UserDetailInfo\"\"\n\x0fGetJSAPISignReq\x12\x0f\n\x07req_url\x18\x01 \x01(\t\"d\n\x0fGetJSAPISignRes\x12\x10\n\x08pa_appid\x18\x01 \x01(\t\x12\x0c\n\x04sign\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x0f\n\x07req_url\x18\x05 \x01(\t\"*\n\x16\x44ownLoadPicResourceReq\x12\x10\n\x08media_id\x18\x01 \x01(\t\",\n\x16\x44ownLoadPicResourceRes\x12\x12\n\nmedia_data\x18\x01 \x01(\x0c\"M\n\x10QueryPaExpertReq\x12\x11\n\tappid_md5\x18\x01 \x01(\x04\x12\x17\n\x0f\x62\x65gin_create_ts\x18\x02 \x01(\x04\x12\r\n\x05limit\x18\x03 \x01(\x04\"+\n\x10QueryPaExpertRes\x12\x17\n\x0fopenid_md5_list\x18\x01 \x03(\x04\"\"\n\rQueryPaTabReq\x12\x11\n\tappid_md5\x18\x01 \x01(\x04\"=\n\rQueryPaTabRes\x12,\n\x08tab_info\x18\x01 \x03(\x0b\x32\x1a.hoosho.commstruct.TabInfo\"\r\n\x0b\x41\x64\x64PaTabReq\"\r\n\x0b\x41\x64\x64PaTabRes\"\x10\n\x0eUpdatePaTabReq\"\x10\n\x0eUpdatePaTabRes\"\x10\n\x0e\x44\x65letePaTabReq\"\x10\n\x0e\x44\x65letePaTabRes')




_PAADDREQ = _descriptor.Descriptor(
  name='PAAddReq',
  full_name='hoosho.pa.PAAddReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_info', full_name='hoosho.pa.PAAddReq.pa_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=100,
)


_PAADDRES = _descriptor.Descriptor(
  name='PAAddRes',
  full_name='hoosho.pa.PAAddRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=112,
)


_PAUPDATEREQ = _descriptor.Descriptor(
  name='PAUpdateReq',
  full_name='hoosho.pa.PAUpdateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_info', full_name='hoosho.pa.PAUpdateReq.pa_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=171,
)


_PAUPDATERES = _descriptor.Descriptor(
  name='PAUpdateRes',
  full_name='hoosho.pa.PAUpdateRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=173,
  serialized_end=186,
)


_PADELETEREQ = _descriptor.Descriptor(
  name='PADeleteReq',
  full_name='hoosho.pa.PADeleteReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid_md5', full_name='hoosho.pa.PADeleteReq.appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=220,
)


_PADELETERES = _descriptor.Descriptor(
  name='PADeleteRes',
  full_name='hoosho.pa.PADeleteRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=222,
  serialized_end=235,
)


_PAGETREQ = _descriptor.Descriptor(
  name='PAGetReq',
  full_name='hoosho.pa.PAGetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid_md5', full_name='hoosho.pa.PAGetReq.appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=237,
  serialized_end=266,
)


_PAGETRES = _descriptor.Descriptor(
  name='PAGetRes',
  full_name='hoosho.pa.PAGetRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_info', full_name='hoosho.pa.PAGetRes.pa_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=268,
  serialized_end=322,
)


_PARSEPREAUTHCODEREQ = _descriptor.Descriptor(
  name='ParsePreAuthCodeReq',
  full_name='hoosho.pa.ParsePreAuthCodeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pre_auth_code', full_name='hoosho.pa.ParsePreAuthCodeReq.pre_auth_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=324,
  serialized_end=368,
)


_PARSEPREAUTHCODERES = _descriptor.Descriptor(
  name='ParsePreAuthCodeRes',
  full_name='hoosho.pa.ParsePreAuthCodeRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_detail_info', full_name='hoosho.pa.ParsePreAuthCodeRes.user_detail_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=370,
  serialized_end=452,
)


_GETJSAPISIGNREQ = _descriptor.Descriptor(
  name='GetJSAPISignReq',
  full_name='hoosho.pa.GetJSAPISignReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_url', full_name='hoosho.pa.GetJSAPISignReq.req_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=454,
  serialized_end=488,
)


_GETJSAPISIGNRES = _descriptor.Descriptor(
  name='GetJSAPISignRes',
  full_name='hoosho.pa.GetJSAPISignRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid', full_name='hoosho.pa.GetJSAPISignRes.pa_appid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sign', full_name='hoosho.pa.GetJSAPISignRes.sign', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='hoosho.pa.GetJSAPISignRes.nonce', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='hoosho.pa.GetJSAPISignRes.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_url', full_name='hoosho.pa.GetJSAPISignRes.req_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=490,
  serialized_end=590,
)


_DOWNLOADPICRESOURCEREQ = _descriptor.Descriptor(
  name='DownLoadPicResourceReq',
  full_name='hoosho.pa.DownLoadPicResourceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='media_id', full_name='hoosho.pa.DownLoadPicResourceReq.media_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=592,
  serialized_end=634,
)


_DOWNLOADPICRESOURCERES = _descriptor.Descriptor(
  name='DownLoadPicResourceRes',
  full_name='hoosho.pa.DownLoadPicResourceRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='media_data', full_name='hoosho.pa.DownLoadPicResourceRes.media_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=636,
  serialized_end=680,
)


_QUERYPAEXPERTREQ = _descriptor.Descriptor(
  name='QueryPaExpertReq',
  full_name='hoosho.pa.QueryPaExpertReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid_md5', full_name='hoosho.pa.QueryPaExpertReq.appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='begin_create_ts', full_name='hoosho.pa.QueryPaExpertReq.begin_create_ts', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='hoosho.pa.QueryPaExpertReq.limit', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=682,
  serialized_end=759,
)


_QUERYPAEXPERTRES = _descriptor.Descriptor(
  name='QueryPaExpertRes',
  full_name='hoosho.pa.QueryPaExpertRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='openid_md5_list', full_name='hoosho.pa.QueryPaExpertRes.openid_md5_list', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=761,
  serialized_end=804,
)


_QUERYPATABREQ = _descriptor.Descriptor(
  name='QueryPaTabReq',
  full_name='hoosho.pa.QueryPaTabReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid_md5', full_name='hoosho.pa.QueryPaTabReq.appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=806,
  serialized_end=840,
)


_QUERYPATABRES = _descriptor.Descriptor(
  name='QueryPaTabRes',
  full_name='hoosho.pa.QueryPaTabRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tab_info', full_name='hoosho.pa.QueryPaTabRes.tab_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=842,
  serialized_end=903,
)


_ADDPATABREQ = _descriptor.Descriptor(
  name='AddPaTabReq',
  full_name='hoosho.pa.AddPaTabReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=905,
  serialized_end=918,
)


_ADDPATABRES = _descriptor.Descriptor(
  name='AddPaTabRes',
  full_name='hoosho.pa.AddPaTabRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=920,
  serialized_end=933,
)


_UPDATEPATABREQ = _descriptor.Descriptor(
  name='UpdatePaTabReq',
  full_name='hoosho.pa.UpdatePaTabReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=935,
  serialized_end=951,
)


_UPDATEPATABRES = _descriptor.Descriptor(
  name='UpdatePaTabRes',
  full_name='hoosho.pa.UpdatePaTabRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=953,
  serialized_end=969,
)


_DELETEPATABREQ = _descriptor.Descriptor(
  name='DeletePaTabReq',
  full_name='hoosho.pa.DeletePaTabReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=971,
  serialized_end=987,
)


_DELETEPATABRES = _descriptor.Descriptor(
  name='DeletePaTabRes',
  full_name='hoosho.pa.DeletePaTabRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=989,
  serialized_end=1005,
)

_PAADDREQ.fields_by_name['pa_info'].message_type = comm_struct_pb2._PAINFO
_PAUPDATEREQ.fields_by_name['pa_info'].message_type = comm_struct_pb2._PAINFO
_PAGETRES.fields_by_name['pa_info'].message_type = comm_struct_pb2._PAINFO
_PARSEPREAUTHCODERES.fields_by_name['user_detail_info'].message_type = comm_struct_pb2._USERDETAILINFO
_QUERYPATABRES.fields_by_name['tab_info'].message_type = comm_struct_pb2._TABINFO
DESCRIPTOR.message_types_by_name['PAAddReq'] = _PAADDREQ
DESCRIPTOR.message_types_by_name['PAAddRes'] = _PAADDRES
DESCRIPTOR.message_types_by_name['PAUpdateReq'] = _PAUPDATEREQ
DESCRIPTOR.message_types_by_name['PAUpdateRes'] = _PAUPDATERES
DESCRIPTOR.message_types_by_name['PADeleteReq'] = _PADELETEREQ
DESCRIPTOR.message_types_by_name['PADeleteRes'] = _PADELETERES
DESCRIPTOR.message_types_by_name['PAGetReq'] = _PAGETREQ
DESCRIPTOR.message_types_by_name['PAGetRes'] = _PAGETRES
DESCRIPTOR.message_types_by_name['ParsePreAuthCodeReq'] = _PARSEPREAUTHCODEREQ
DESCRIPTOR.message_types_by_name['ParsePreAuthCodeRes'] = _PARSEPREAUTHCODERES
DESCRIPTOR.message_types_by_name['GetJSAPISignReq'] = _GETJSAPISIGNREQ
DESCRIPTOR.message_types_by_name['GetJSAPISignRes'] = _GETJSAPISIGNRES
DESCRIPTOR.message_types_by_name['DownLoadPicResourceReq'] = _DOWNLOADPICRESOURCEREQ
DESCRIPTOR.message_types_by_name['DownLoadPicResourceRes'] = _DOWNLOADPICRESOURCERES
DESCRIPTOR.message_types_by_name['QueryPaExpertReq'] = _QUERYPAEXPERTREQ
DESCRIPTOR.message_types_by_name['QueryPaExpertRes'] = _QUERYPAEXPERTRES
DESCRIPTOR.message_types_by_name['QueryPaTabReq'] = _QUERYPATABREQ
DESCRIPTOR.message_types_by_name['QueryPaTabRes'] = _QUERYPATABRES
DESCRIPTOR.message_types_by_name['AddPaTabReq'] = _ADDPATABREQ
DESCRIPTOR.message_types_by_name['AddPaTabRes'] = _ADDPATABRES
DESCRIPTOR.message_types_by_name['UpdatePaTabReq'] = _UPDATEPATABREQ
DESCRIPTOR.message_types_by_name['UpdatePaTabRes'] = _UPDATEPATABRES
DESCRIPTOR.message_types_by_name['DeletePaTabReq'] = _DELETEPATABREQ
DESCRIPTOR.message_types_by_name['DeletePaTabRes'] = _DELETEPATABRES

class PAAddReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAADDREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.PAAddReq)

class PAAddRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAADDRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.PAAddRes)

class PAUpdateReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAUPDATEREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.PAUpdateReq)

class PAUpdateRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAUPDATERES

  # @@protoc_insertion_point(class_scope:hoosho.pa.PAUpdateRes)

class PADeleteReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PADELETEREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.PADeleteReq)

class PADeleteRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PADELETERES

  # @@protoc_insertion_point(class_scope:hoosho.pa.PADeleteRes)

class PAGetReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAGETREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.PAGetReq)

class PAGetRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAGETRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.PAGetRes)

class ParsePreAuthCodeReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARSEPREAUTHCODEREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.ParsePreAuthCodeReq)

class ParsePreAuthCodeRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARSEPREAUTHCODERES

  # @@protoc_insertion_point(class_scope:hoosho.pa.ParsePreAuthCodeRes)

class GetJSAPISignReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETJSAPISIGNREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.GetJSAPISignReq)

class GetJSAPISignRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETJSAPISIGNRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.GetJSAPISignRes)

class DownLoadPicResourceReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOWNLOADPICRESOURCEREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.DownLoadPicResourceReq)

class DownLoadPicResourceRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOWNLOADPICRESOURCERES

  # @@protoc_insertion_point(class_scope:hoosho.pa.DownLoadPicResourceRes)

class QueryPaExpertReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYPAEXPERTREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.QueryPaExpertReq)

class QueryPaExpertRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYPAEXPERTRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.QueryPaExpertRes)

class QueryPaTabReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYPATABREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.QueryPaTabReq)

class QueryPaTabRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYPATABRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.QueryPaTabRes)

class AddPaTabReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDPATABREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.AddPaTabReq)

class AddPaTabRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDPATABRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.AddPaTabRes)

class UpdatePaTabReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEPATABREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.UpdatePaTabReq)

class UpdatePaTabRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEPATABRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.UpdatePaTabRes)

class DeletePaTabReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEPATABREQ

  # @@protoc_insertion_point(class_scope:hoosho.pa.DeletePaTabReq)

class DeletePaTabRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEPATABRES

  # @@protoc_insertion_point(class_scope:hoosho.pa.DeletePaTabRes)


# @@protoc_insertion_point(module_scope)
