# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_sysnotice.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import comm_struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_sysnotice.proto',
  package='hoosho.sysnotice',
  serialized_pb='\n\x13msg_sysnotice.proto\x12\x10hoosho.sysnotice\x1a\x11\x63omm_struct.proto\"d\n\x14QuerySysNoticeNewReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x12\n\nopenid_md5\x18\x02 \x01(\x04\x12\x10\n\x08limit_ts\x18\x03 \x01(\x04\x12\x10\n\x08pagesize\x18\x04 \x01(\r\"M\n\x14QuerySysNoticeNewRes\x12\x35\n\x0fsys_notice_list\x18\x01 \x03(\x0b\x32\x1c.hoosho.commstruct.SysNotice\"d\n\x14QuerySysNoticeAllReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x12\n\nopenid_md5\x18\x02 \x01(\x04\x12\x10\n\x08limit_ts\x18\x03 \x01(\x04\x12\x10\n\x08pagesize\x18\x04 \x01(\r\"M\n\x14QuerySysNoticeAllRes\x12\x35\n\x0fsys_notice_list\x18\x01 \x03(\x0b\x32\x1c.hoosho.commstruct.SysNotice\"C\n\x0f\x41\x64\x64SysNoticeReq\x12\x30\n\nsys_notice\x18\x01 \x01(\x0b\x32\x1c.hoosho.commstruct.SysNotice\"\x11\n\x0f\x41\x64\x64SysNoticeRes\"F\n\x12UpdateSysNoticeReq\x12\x30\n\nsys_notice\x18\x01 \x01(\x0b\x32\x1c.hoosho.commstruct.SysNotice\"\x14\n\x12UpdateSysNoticeRes\"=\n\x12\x44\x65leteSysNoticeReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x11\n\tcreate_ts\x18\x02 \x01(\x04\"\x14\n\x12\x44\x65leteSysNoticeRes\"I\n\x1dQueryNoticeNotifySysNoticeReq\x12\x14\n\x0cpa_appid_md5\x18\x01 \x01(\x04\x12\x12\n\nopenid_md5\x18\x02 \x01(\x04\"/\n\x1dQueryNoticeNotifySysNoticeRes\x12\x0e\n\x06status\x18\x01 \x01(\r')




_QUERYSYSNOTICENEWREQ = _descriptor.Descriptor(
  name='QuerySysNoticeNewReq',
  full_name='hoosho.sysnotice.QuerySysNoticeNewReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.sysnotice.QuerySysNoticeNewReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.sysnotice.QuerySysNoticeNewReq.openid_md5', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_ts', full_name='hoosho.sysnotice.QuerySysNoticeNewReq.limit_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='hoosho.sysnotice.QuerySysNoticeNewReq.pagesize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=160,
)


_QUERYSYSNOTICENEWRES = _descriptor.Descriptor(
  name='QuerySysNoticeNewRes',
  full_name='hoosho.sysnotice.QuerySysNoticeNewRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_notice_list', full_name='hoosho.sysnotice.QuerySysNoticeNewRes.sys_notice_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=239,
)


_QUERYSYSNOTICEALLREQ = _descriptor.Descriptor(
  name='QuerySysNoticeAllReq',
  full_name='hoosho.sysnotice.QuerySysNoticeAllReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.sysnotice.QuerySysNoticeAllReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.sysnotice.QuerySysNoticeAllReq.openid_md5', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_ts', full_name='hoosho.sysnotice.QuerySysNoticeAllReq.limit_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='hoosho.sysnotice.QuerySysNoticeAllReq.pagesize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=341,
)


_QUERYSYSNOTICEALLRES = _descriptor.Descriptor(
  name='QuerySysNoticeAllRes',
  full_name='hoosho.sysnotice.QuerySysNoticeAllRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_notice_list', full_name='hoosho.sysnotice.QuerySysNoticeAllRes.sys_notice_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=343,
  serialized_end=420,
)


_ADDSYSNOTICEREQ = _descriptor.Descriptor(
  name='AddSysNoticeReq',
  full_name='hoosho.sysnotice.AddSysNoticeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_notice', full_name='hoosho.sysnotice.AddSysNoticeReq.sys_notice', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=422,
  serialized_end=489,
)


_ADDSYSNOTICERES = _descriptor.Descriptor(
  name='AddSysNoticeRes',
  full_name='hoosho.sysnotice.AddSysNoticeRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=491,
  serialized_end=508,
)


_UPDATESYSNOTICEREQ = _descriptor.Descriptor(
  name='UpdateSysNoticeReq',
  full_name='hoosho.sysnotice.UpdateSysNoticeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_notice', full_name='hoosho.sysnotice.UpdateSysNoticeReq.sys_notice', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=510,
  serialized_end=580,
)


_UPDATESYSNOTICERES = _descriptor.Descriptor(
  name='UpdateSysNoticeRes',
  full_name='hoosho.sysnotice.UpdateSysNoticeRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=582,
  serialized_end=602,
)


_DELETESYSNOTICEREQ = _descriptor.Descriptor(
  name='DeleteSysNoticeReq',
  full_name='hoosho.sysnotice.DeleteSysNoticeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.sysnotice.DeleteSysNoticeReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_ts', full_name='hoosho.sysnotice.DeleteSysNoticeReq.create_ts', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=604,
  serialized_end=665,
)


_DELETESYSNOTICERES = _descriptor.Descriptor(
  name='DeleteSysNoticeRes',
  full_name='hoosho.sysnotice.DeleteSysNoticeRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=667,
  serialized_end=687,
)


_QUERYNOTICENOTIFYSYSNOTICEREQ = _descriptor.Descriptor(
  name='QueryNoticeNotifySysNoticeReq',
  full_name='hoosho.sysnotice.QueryNoticeNotifySysNoticeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pa_appid_md5', full_name='hoosho.sysnotice.QueryNoticeNotifySysNoticeReq.pa_appid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.sysnotice.QueryNoticeNotifySysNoticeReq.openid_md5', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=689,
  serialized_end=762,
)


_QUERYNOTICENOTIFYSYSNOTICERES = _descriptor.Descriptor(
  name='QueryNoticeNotifySysNoticeRes',
  full_name='hoosho.sysnotice.QueryNoticeNotifySysNoticeRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='hoosho.sysnotice.QueryNoticeNotifySysNoticeRes.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=764,
  serialized_end=811,
)

_QUERYSYSNOTICENEWRES.fields_by_name['sys_notice_list'].message_type = comm_struct_pb2._SYSNOTICE
_QUERYSYSNOTICEALLRES.fields_by_name['sys_notice_list'].message_type = comm_struct_pb2._SYSNOTICE
_ADDSYSNOTICEREQ.fields_by_name['sys_notice'].message_type = comm_struct_pb2._SYSNOTICE
_UPDATESYSNOTICEREQ.fields_by_name['sys_notice'].message_type = comm_struct_pb2._SYSNOTICE
DESCRIPTOR.message_types_by_name['QuerySysNoticeNewReq'] = _QUERYSYSNOTICENEWREQ
DESCRIPTOR.message_types_by_name['QuerySysNoticeNewRes'] = _QUERYSYSNOTICENEWRES
DESCRIPTOR.message_types_by_name['QuerySysNoticeAllReq'] = _QUERYSYSNOTICEALLREQ
DESCRIPTOR.message_types_by_name['QuerySysNoticeAllRes'] = _QUERYSYSNOTICEALLRES
DESCRIPTOR.message_types_by_name['AddSysNoticeReq'] = _ADDSYSNOTICEREQ
DESCRIPTOR.message_types_by_name['AddSysNoticeRes'] = _ADDSYSNOTICERES
DESCRIPTOR.message_types_by_name['UpdateSysNoticeReq'] = _UPDATESYSNOTICEREQ
DESCRIPTOR.message_types_by_name['UpdateSysNoticeRes'] = _UPDATESYSNOTICERES
DESCRIPTOR.message_types_by_name['DeleteSysNoticeReq'] = _DELETESYSNOTICEREQ
DESCRIPTOR.message_types_by_name['DeleteSysNoticeRes'] = _DELETESYSNOTICERES
DESCRIPTOR.message_types_by_name['QueryNoticeNotifySysNoticeReq'] = _QUERYNOTICENOTIFYSYSNOTICEREQ
DESCRIPTOR.message_types_by_name['QueryNoticeNotifySysNoticeRes'] = _QUERYNOTICENOTIFYSYSNOTICERES

class QuerySysNoticeNewReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYSYSNOTICENEWREQ

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.QuerySysNoticeNewReq)

class QuerySysNoticeNewRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYSYSNOTICENEWRES

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.QuerySysNoticeNewRes)

class QuerySysNoticeAllReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYSYSNOTICEALLREQ

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.QuerySysNoticeAllReq)

class QuerySysNoticeAllRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYSYSNOTICEALLRES

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.QuerySysNoticeAllRes)

class AddSysNoticeReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDSYSNOTICEREQ

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.AddSysNoticeReq)

class AddSysNoticeRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDSYSNOTICERES

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.AddSysNoticeRes)

class UpdateSysNoticeReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATESYSNOTICEREQ

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.UpdateSysNoticeReq)

class UpdateSysNoticeRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATESYSNOTICERES

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.UpdateSysNoticeRes)

class DeleteSysNoticeReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETESYSNOTICEREQ

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.DeleteSysNoticeReq)

class DeleteSysNoticeRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETESYSNOTICERES

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.DeleteSysNoticeRes)

class QueryNoticeNotifySysNoticeReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICENOTIFYSYSNOTICEREQ

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.QueryNoticeNotifySysNoticeReq)

class QueryNoticeNotifySysNoticeRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYNOTICENOTIFYSYSNOTICERES

  # @@protoc_insertion_point(class_scope:hoosho.sysnotice.QueryNoticeNotifySysNoticeRes)


# @@protoc_insertion_point(module_scope)
