# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_mark.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import comm_struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_mark.proto',
  package='hoosho.usermark',
  serialized_pb='\n\x0emsg_mark.proto\x12\x0fhoosho.usermark\x1a\x11\x63omm_struct.proto\"&\n\x10QueryUserMarkReq\x12\x12\n\nopenid_md5\x18\x01 \x01(\x04\"A\n\x10QueryUserMarkRes\x12-\n\x08usermark\x18\x01 \x03(\x0b\x32\x1b.hoosho.commstruct.UserMark\"?\n\x0e\x41\x64\x64UserMarkReq\x12-\n\x08usermark\x18\x01 \x01(\x0b\x32\x1b.hoosho.commstruct.UserMark\"\x10\n\x0e\x41\x64\x64UserMarkRes\"\x13\n\x11UpdateUserMarkReq\"\x13\n\x11UpdateUserMarkRes\"\'\n\x11\x44\x65leteUserMarkReq\x12\x12\n\nopenid_md5\x18\x01 \x01(\x04\"\x13\n\x11\x44\x65leteUserMarkRes')




_QUERYUSERMARKREQ = _descriptor.Descriptor(
  name='QueryUserMarkReq',
  full_name='hoosho.usermark.QueryUserMarkReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.usermark.QueryUserMarkReq.openid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=92,
)


_QUERYUSERMARKRES = _descriptor.Descriptor(
  name='QueryUserMarkRes',
  full_name='hoosho.usermark.QueryUserMarkRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usermark', full_name='hoosho.usermark.QueryUserMarkRes.usermark', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=159,
)


_ADDUSERMARKREQ = _descriptor.Descriptor(
  name='AddUserMarkReq',
  full_name='hoosho.usermark.AddUserMarkReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usermark', full_name='hoosho.usermark.AddUserMarkReq.usermark', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=161,
  serialized_end=224,
)


_ADDUSERMARKRES = _descriptor.Descriptor(
  name='AddUserMarkRes',
  full_name='hoosho.usermark.AddUserMarkRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=226,
  serialized_end=242,
)


_UPDATEUSERMARKREQ = _descriptor.Descriptor(
  name='UpdateUserMarkReq',
  full_name='hoosho.usermark.UpdateUserMarkReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=244,
  serialized_end=263,
)


_UPDATEUSERMARKRES = _descriptor.Descriptor(
  name='UpdateUserMarkRes',
  full_name='hoosho.usermark.UpdateUserMarkRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=265,
  serialized_end=284,
)


_DELETEUSERMARKREQ = _descriptor.Descriptor(
  name='DeleteUserMarkReq',
  full_name='hoosho.usermark.DeleteUserMarkReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='openid_md5', full_name='hoosho.usermark.DeleteUserMarkReq.openid_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=286,
  serialized_end=325,
)


_DELETEUSERMARKRES = _descriptor.Descriptor(
  name='DeleteUserMarkRes',
  full_name='hoosho.usermark.DeleteUserMarkRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=327,
  serialized_end=346,
)

_QUERYUSERMARKRES.fields_by_name['usermark'].message_type = comm_struct_pb2._USERMARK
_ADDUSERMARKREQ.fields_by_name['usermark'].message_type = comm_struct_pb2._USERMARK
DESCRIPTOR.message_types_by_name['QueryUserMarkReq'] = _QUERYUSERMARKREQ
DESCRIPTOR.message_types_by_name['QueryUserMarkRes'] = _QUERYUSERMARKRES
DESCRIPTOR.message_types_by_name['AddUserMarkReq'] = _ADDUSERMARKREQ
DESCRIPTOR.message_types_by_name['AddUserMarkRes'] = _ADDUSERMARKRES
DESCRIPTOR.message_types_by_name['UpdateUserMarkReq'] = _UPDATEUSERMARKREQ
DESCRIPTOR.message_types_by_name['UpdateUserMarkRes'] = _UPDATEUSERMARKRES
DESCRIPTOR.message_types_by_name['DeleteUserMarkReq'] = _DELETEUSERMARKREQ
DESCRIPTOR.message_types_by_name['DeleteUserMarkRes'] = _DELETEUSERMARKRES

class QueryUserMarkReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYUSERMARKREQ

  # @@protoc_insertion_point(class_scope:hoosho.usermark.QueryUserMarkReq)

class QueryUserMarkRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYUSERMARKRES

  # @@protoc_insertion_point(class_scope:hoosho.usermark.QueryUserMarkRes)

class AddUserMarkReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDUSERMARKREQ

  # @@protoc_insertion_point(class_scope:hoosho.usermark.AddUserMarkReq)

class AddUserMarkRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDUSERMARKRES

  # @@protoc_insertion_point(class_scope:hoosho.usermark.AddUserMarkRes)

class UpdateUserMarkReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEUSERMARKREQ

  # @@protoc_insertion_point(class_scope:hoosho.usermark.UpdateUserMarkReq)

class UpdateUserMarkRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEUSERMARKRES

  # @@protoc_insertion_point(class_scope:hoosho.usermark.UpdateUserMarkRes)

class DeleteUserMarkReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEUSERMARKREQ

  # @@protoc_insertion_point(class_scope:hoosho.usermark.DeleteUserMarkReq)

class DeleteUserMarkRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEUSERMARKRES

  # @@protoc_insertion_point(class_scope:hoosho.usermark.DeleteUserMarkRes)


# @@protoc_insertion_point(module_scope)
