# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import comm_struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_test.proto',
  package='hoosho.test',
  serialized_pb='\n\x0emsg_test.proto\x12\x0bhoosho.test\x1a\x11\x63omm_struct.proto\"\x16\n\x08QueryReq\x12\n\n\x02id\x18\x01 \x01(\r\":\n\x08QueryRes\x12.\n\tuser_info\x18\x01 \x01(\x0b\x32\x1b.hoosho.commstruct.UserInfo\"8\n\x06\x41\x64\x64Req\x12.\n\tuser_info\x18\x01 \x01(\x0b\x32\x1b.hoosho.commstruct.UserInfo\"\x08\n\x06\x41\x64\x64Res\";\n\tUpdateReq\x12.\n\tuser_info\x18\x01 \x01(\x0b\x32\x1b.hoosho.commstruct.UserInfo\"\x0b\n\tUpdateRes\"\x17\n\tDeleteReq\x12\n\n\x02id\x18\x01 \x01(\r\"\x0b\n\tDeleteRes')




_QUERYREQ = _descriptor.Descriptor(
  name='QueryReq',
  full_name='hoosho.test.QueryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hoosho.test.QueryReq.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=72,
)


_QUERYRES = _descriptor.Descriptor(
  name='QueryRes',
  full_name='hoosho.test.QueryRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_info', full_name='hoosho.test.QueryRes.user_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=132,
)


_ADDREQ = _descriptor.Descriptor(
  name='AddReq',
  full_name='hoosho.test.AddReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_info', full_name='hoosho.test.AddReq.user_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=190,
)


_ADDRES = _descriptor.Descriptor(
  name='AddRes',
  full_name='hoosho.test.AddRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=192,
  serialized_end=200,
)


_UPDATEREQ = _descriptor.Descriptor(
  name='UpdateReq',
  full_name='hoosho.test.UpdateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_info', full_name='hoosho.test.UpdateReq.user_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=202,
  serialized_end=261,
)


_UPDATERES = _descriptor.Descriptor(
  name='UpdateRes',
  full_name='hoosho.test.UpdateRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=263,
  serialized_end=274,
)


_DELETEREQ = _descriptor.Descriptor(
  name='DeleteReq',
  full_name='hoosho.test.DeleteReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hoosho.test.DeleteReq.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=276,
  serialized_end=299,
)


_DELETERES = _descriptor.Descriptor(
  name='DeleteRes',
  full_name='hoosho.test.DeleteRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=301,
  serialized_end=312,
)

_QUERYRES.fields_by_name['user_info'].message_type = comm_struct_pb2._USERINFO
_ADDREQ.fields_by_name['user_info'].message_type = comm_struct_pb2._USERINFO
_UPDATEREQ.fields_by_name['user_info'].message_type = comm_struct_pb2._USERINFO
DESCRIPTOR.message_types_by_name['QueryReq'] = _QUERYREQ
DESCRIPTOR.message_types_by_name['QueryRes'] = _QUERYRES
DESCRIPTOR.message_types_by_name['AddReq'] = _ADDREQ
DESCRIPTOR.message_types_by_name['AddRes'] = _ADDRES
DESCRIPTOR.message_types_by_name['UpdateReq'] = _UPDATEREQ
DESCRIPTOR.message_types_by_name['UpdateRes'] = _UPDATERES
DESCRIPTOR.message_types_by_name['DeleteReq'] = _DELETEREQ
DESCRIPTOR.message_types_by_name['DeleteRes'] = _DELETERES

class QueryReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYREQ

  # @@protoc_insertion_point(class_scope:hoosho.test.QueryReq)

class QueryRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYRES

  # @@protoc_insertion_point(class_scope:hoosho.test.QueryRes)

class AddReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDREQ

  # @@protoc_insertion_point(class_scope:hoosho.test.AddReq)

class AddRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDRES

  # @@protoc_insertion_point(class_scope:hoosho.test.AddRes)

class UpdateReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEREQ

  # @@protoc_insertion_point(class_scope:hoosho.test.UpdateReq)

class UpdateRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATERES

  # @@protoc_insertion_point(class_scope:hoosho.test.UpdateRes)

class DeleteReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEREQ

  # @@protoc_insertion_point(class_scope:hoosho.test.DeleteReq)

class DeleteRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETERES

  # @@protoc_insertion_point(class_scope:hoosho.test.DeleteRes)


# @@protoc_insertion_point(module_scope)
