# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_config.proto',
  package='hoosho.config',
  serialized_pb='\n\x10msg_config.proto\x12\rhoosho.config\"\x12\n\x10HooshoNOApplyReq\"%\n\x10HooshoNOApplyRes\x12\x11\n\thoosho_no\x18\x01 \x01(\x04')




_HOOSHONOAPPLYREQ = _descriptor.Descriptor(
  name='HooshoNOApplyReq',
  full_name='hoosho.config.HooshoNOApplyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=53,
)


_HOOSHONOAPPLYRES = _descriptor.Descriptor(
  name='HooshoNOApplyRes',
  full_name='hoosho.config.HooshoNOApplyRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hoosho_no', full_name='hoosho.config.HooshoNOApplyRes.hoosho_no', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['HooshoNOApplyReq'] = _HOOSHONOAPPLYREQ
DESCRIPTOR.message_types_by_name['HooshoNOApplyRes'] = _HOOSHONOAPPLYRES

class HooshoNOApplyReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOOSHONOAPPLYREQ

  # @@protoc_insertion_point(class_scope:hoosho.config.HooshoNOApplyReq)

class HooshoNOApplyRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOOSHONOAPPLYRES

  # @@protoc_insertion_point(class_scope:hoosho.config.HooshoNOApplyRes)


# @@protoc_insertion_point(module_scope)
